# -*- mode: ruby -*-
# vi: set ft=ruby :


require 'getoptlong'

opts = GetoptLong.new(
  [ '--os_user_name', GetoptLong::REQUIRED_ARGUMENT  ],
  [ '--git_user_name', GetoptLong::OPTIONAL_ARGUMENT ],
  [ '--git_email', GetoptLong::OPTIONAL_ARGUMENT ]
)

osUserName=''
gitUserName=''
gitEmail=''

opts.each do |opt, arg|
  case opt
    when '--os_user_name'
      osUserName=arg
    when '--git_user_name'
      gitUserName=arg
    when '--git_email'
      gitEmail=arg
  end
end

provisioned = File.exist?(".vagrant/machines/default/virtualbox/action_provision")

if ARGV[0] == 'up' && osUserName == '' && !provisioned
  puts "To provision a new machine, call with --os_user_name=<OS user name> parameter"
  exit 0
end

Vagrant.configure(2) do |config|
	config.vm.box = "centos/7"

	config.vm.synced_folder "../../", "/vagrant", type: "virtualbox"
	
	config.vm.network "forwarded_port", guest: 8080, host: 8080
	config.vm.network "forwarded_port", guest: 9990, host: 9990
	config.vm.network "forwarded_port", guest: 5432, host: 5432

	config.vm.provider :virtualbox do |vb|
		vb.customize ["modifyvm", :id,
			"--name", "links-vagrant",
			"--memory", "8192",
			"--cpus", "4"]
	end

	config.vm.provision "shell", inline: <<-SHELL
		curl -O https://raw.githubusercontent.com/bkaminnski/links/master/ci/provision.sh
		chmod 755 ./provision.sh
		./provision.sh --os_user_name #{osUserName} --git_user_name "#{gitUserName}" --git_email #{gitEmail}
	SHELL
end
